# Generated by Django 5.1.2 on 2025-09-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_alter_order_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('GBP', 'British Pound (£)'), ('EUR', 'Euro (€)')], default='GBP', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.CharField(choices=[('GBP', 'British Pound (£)'), ('EUR', 'Euro (€)')], default='GBP', max_length=3),
        ),
    ]
